users:
  
name: web
  ssh-authorized-keys:-ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC0zSrnP4MN5zGFOPrIGrNCo6K/5FBu6k1PIAAKMjlnnUtA5201PzQ0kNsZqBtL68jWmPUM4gxGYDe8EOlH3XJKWy/1E1kUK5Z+Cwqmm7L+BwLWarCf2DX8L2BFUEtompOs6qETrXmOaS/T4nhLGu1/VcMzuEVpyMErHyRwQYy/Woq7gSLslC3ruglb/5lK9dWU7VhH6aIlX+xusVJCAKI0O5G+4dg9v4HbPC3eQAttchw343PjPnkPYQTXGnosFHQNRnujAKJXhjI7FJ2xKqe/IpV63CFYO4WLw6wQaXeKo5sWXHvlYZ0ovg3LLh2Pd7cWHG+h3FoHS2Law4RwZpzBvTzUs3q2gkLruMWBvwx/QM3szrbRVPGxCjqfjK00YFvUO3NQJSmrYSLapwXA7kbKT5oBco5PeZnZLNMuxzbmvAe0namRc8Ffkm+N+2+PjhKv+GKAYgM0Yae4Of2j398jgY47jGY7M2b0kv06uZJwe3+Yvsgcq2RZfOIfc2LAgQ97PFnypK2E6DGE5OkuEK8W6vbmU2j7TjVvJdnvQoPdGWLmYpTG5d9hnjQpmZncHfI90NCa+zdRvHMP2986esp4V+57pj/RUrzOhw83J+0ETVAtqRODxTOToYGKi33ymXcYyZJYUodWVKvAHwyTzbEQF51QWNuF1c1QrmBagKkI1Q== jas@Jashan1

packages:
  
nginx
nmap